### PR TITLE
Testing a change to image highlighting

### PR DESCRIPTION
**Pull request by SteveLasker**
Testing a way to highlight where the user should focus, based on the doc reference
- Includes a blue box, with the same color as the RKVST logo: `#00AEEF`
  - 4 pix solid border with a bottom/right drop shadow (using TechSmith snagit)
- "Steps" which are based on the doc numbered list. Using snagit editor features and the RKVS color scheme

<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Comment by pcnorth** [comment]
This is a good idea and would allow us to use fewer screenchots by having multiple steps on one screenshot.
The UI is changing so frequently right now it might be better to wait a while before working on this though.

**Comment by SteveLasker** [comment]
cc @beekman33

**Comment by SteveLasker** [comment]
I've done a first pass of validation. The multiple steps could be converted to a script, creating the `rkvst-bearer.txt` file. And, if we like this, we can update the other docs that need a bearer token to reference the same file. We may want to store the `rkvst-bearer.txt` in some local temp directory, if we can agree where that would be across Mac, Linux and WSL

**Review by pcnorth — APPROVED** [review]
This looks better and makes the docs more efficient for customers

**Comment by SteveLasker** [comment]
Thanks, @pcnorth 
I’ll make a PR to the style guide and when we get to a UX stability point we can scrub through the images. 
Kike you mentioned above, the numbered steps and border/highlights can likely reduce the number of images to manage.

**Comment by SteveLasker** [comment]
moving to #671

**Pull request closed without merging**
